name:                bits-extra
version:             0.0.0.1
github:              "githubuser/bits-extra"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/bits-extra#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bits-extra-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bits-extra

tests:
  bits-extra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bits-extra
